name: Test and Merge

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Check for failed tests
        run: |
          if [ -f "test-results.xml" ]; then failed=$(grep -c "<failure" test-results.xml)
          if [ "$failed" -gt 0 ]; then
            echo "Some tests failed. Please fix them before merging."
            exit 1
          fi
          fi

